import type { Metadata } from "next";
import { Plus_Jakarta_Sans, DM_Serif_Display } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import ClientLayout from "@/components/ClientLayout";

const PlusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plusjakarta-sans",
  subsets: ["latin"],
  display: "swap",
});

const DMSerifDisplay = DM_Serif_Display({
  weight: "400",
  variable: "--font-dm-serif-display",
  subsets: ["latin"],
  display: "swap",
});

const gloss = localFont({
  src: "./fonts/Gloss_And_Bloom.ttf",
  style: "normal",
  variable: "--font-gloss",
});

export const metadata: Metadata = {
  title: "SailAway",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen bg-white ${PlusJakartaSans.variable} ${DMSerifDisplay.variable} ${gloss.variable} antialiased`}
      >
        <StoreProvider>
          <ClientLayout>{children}</ClientLayout>
        </StoreProvider>
      </body>
    </html>
  );
}